import { useEffect, useState } from 'react'
import { Link, Navigate, Outlet, Route, Routes, useNavigate } from 'react-router-dom'
import api from '../services/api'
import { useAuth } from '../context/useAuth'
import { TechnicianListPage, TechnicianProfilePage } from '../features/technicians/TechnicianDiscovery'
import DiagnosisFlow from '../features/diagnosis/DiagnosisFlow'
import { BookingPage, BookingListPage, BookingDetailPage } from '../features/repairs/BookingFlow'
import TechnicianDashboard from '../features/technicians/TechnicianDashboard'
import CustomerDashboard from '../features/customer/CustomerDashboard'
import ProfilePage from '../features/profile/ProfilePage'

function AppShell() {
  const { user, isAuthenticated, logout } = useAuth()
  const dashboard = user?.role === 'TECHNICIAN' ? '/technician/dashboard' : '/customer/dashboard'
  return <div className="min-h-screen bg-slate-50 text-slate-900"><header className="border-b border-slate-200 bg-white"><nav className="mx-auto flex max-w-7xl items-center justify-between px-6 py-4" aria-label="Primary navigation"><Link to={isAuthenticated ? dashboard : '/'} className="text-xl font-bold tracking-tight">Local<span className="text-blue-600">Repair</span></Link><div className="flex items-center gap-2 text-sm font-semibold">{isAuthenticated ? <>{user.role === 'CUSTOMER' && <Link to="/technicians" className="rounded-lg px-3 py-2 text-slate-600 hover:bg-slate-100">Find technician</Link>}<Link to={dashboard} className="rounded-lg px-3 py-2 text-slate-600 hover:bg-slate-100">Dashboard</Link>{user.role === 'CUSTOMER' && <Link to="/customer/repairs" className="hidden rounded-lg px-3 py-2 text-slate-600 hover:bg-slate-100 sm:block">My bookings</Link>}<Link to="/profile" className="rounded-lg px-3 py-2 text-slate-600 hover:bg-slate-100">Profile</Link><button onClick={logout} className="rounded-lg border border-slate-300 px-3 py-2 text-slate-600 hover:bg-slate-50">Log out</button></> : <><Link to="/login" className="rounded-lg px-3 py-2 text-slate-600 hover:bg-slate-100">Log in</Link><Link to="/register" className="rounded-lg bg-blue-600 px-4 py-2 text-white hover:bg-blue-700">Get started</Link></>}</div></nav></header><Outlet /></div>
}

function Landing() {
  const [apiStatus, setApiStatus] = useState('checking')
  useEffect(() => { api.get('/health').then(() => setApiStatus('connected')).catch(() => setApiStatus('unavailable')) }, [])
  return <main><section className="mx-auto grid max-w-7xl gap-12 px-6 py-20 lg:grid-cols-[1.1fr_0.9fr] lg:items-center"><div><p className="mb-4 text-sm font-bold uppercase tracking-[0.18em] text-blue-600">Trusted local service</p><h1 className="max-w-2xl text-4xl font-bold tracking-tight sm:text-6xl">Reliable appliance repair, close to home.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-600">Find verified technicians, get clear estimates, and keep your repair moving with confidence.</p><Link to="/diagnosis" className="mt-8 inline-block rounded-lg bg-blue-600 px-5 py-3 font-semibold text-white hover:bg-blue-700">Diagnose your repair</Link></div><div className="rounded-2xl border border-blue-100 bg-blue-50 p-8"><p className="text-sm font-semibold text-blue-700">LocalRepair</p><h2 className="mt-3 text-2xl font-bold">Your repair journey starts here.</h2><p className="mt-3 leading-7 text-slate-600">Start with a quick, transparent diagnosis suggestion before finding a verified technician.</p><p className={`mt-6 text-sm font-semibold ${apiStatus === 'connected' ? 'text-green-600' : apiStatus === 'unavailable' ? 'text-red-600' : 'text-slate-500'}`}>{apiStatus === 'checking' ? 'Checking API connection…' : apiStatus === 'connected' ? 'API connected' : 'API unavailable — check the backend'}</p></div></section></main>
}

function AuthPage({ mode }) {
  const isRegister = mode === 'register'; const { login, register, isAuthenticated } = useAuth(); const navigate = useNavigate(); const [form, setForm] = useState({ name: '', email: '', password: '', confirmPassword: '', role: 'CUSTOMER' }); const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
  if (isAuthenticated) return <Navigate to={JSON.parse(localStorage.getItem('localrepair_user') || '{}').role === 'TECHNICIAN' ? '/technician/dashboard' : '/customer/dashboard'} replace />
  const submit = async (event) => { event.preventDefault(); setError(''); if (isRegister && form.password !== form.confirmPassword) { setError('Passwords do not match'); return } setLoading(true); try { const currentUser = isRegister ? await register({ name: form.name, email: form.email, password: form.password, role: form.role }) : await login({ email: form.email, password: form.password }); navigate(currentUser.role === 'TECHNICIAN' ? '/technician/dashboard' : '/customer/dashboard') } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to complete the request') } finally { setLoading(false) } }
  return <main className="mx-auto max-w-lg px-6 py-16"><h1 className="text-3xl font-bold">{isRegister ? 'Create your account' : 'Welcome back'}</h1><p className="mt-2 text-slate-600">{isRegister ? 'Connect with trusted local repair help.' : 'Sign in to continue to LocalRepair.'}</p><form onSubmit={submit} className="mt-8 space-y-5 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">{isRegister && <label className="block text-sm font-semibold">Name<input required minLength="2" maxLength="100" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-3 font-normal" /></label>}<label className="block text-sm font-semibold">Email<input required type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-3 font-normal" /></label><label className="block text-sm font-semibold">Password<input required minLength="8" type="password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-3 font-normal" /></label>{isRegister && <><label className="block text-sm font-semibold">Confirm password<input required minLength="8" type="password" value={form.confirmPassword} onChange={(e) => setForm({ ...form, confirmPassword: e.target.value })} className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-3 font-normal" /></label><label className="block text-sm font-semibold">Account type<select value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value })} className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-3 font-normal"><option value="CUSTOMER">Customer</option><option value="TECHNICIAN">Technician</option></select></label></>} {error && <p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={loading} className="w-full rounded-xl bg-blue-600 px-4 py-3 font-semibold text-white disabled:cursor-not-allowed disabled:opacity-60">{loading ? 'Please wait…' : isRegister ? 'Create account' : 'Log in'}</button><p className="text-center text-sm text-slate-600">{isRegister ? <>Already registered? <Link className="font-semibold text-blue-600" to="/login">Log in</Link></> : <>Need an account? <Link className="font-semibold text-blue-600" to="/register">Register</Link></>}</p></form></main>
}

function ProtectedRoute({ role }) { const { user, loading, isAuthenticated } = useAuth(); if (loading) return <main className="p-10 text-center">Loading your session…</main>; if (!isAuthenticated) return <Navigate to="/login" replace />; if (role && user.role !== role) return <Navigate to={user.role === 'TECHNICIAN' ? '/technician/dashboard' : '/customer/dashboard'} replace />; return <Outlet /> }
function HomeRedirect() { const { user, loading, isAuthenticated } = useAuth(); if (loading) return <main className="p-10 text-center">Loading your session…</main>; return isAuthenticated ? <Navigate to={user.role === 'TECHNICIAN' ? '/technician/dashboard' : '/customer/dashboard'} replace /> : <Landing /> }
export default function AppRoutes() { return <Routes><Route element={<AppShell />}><Route path="/" element={<HomeRedirect />} /><Route path="/login" element={<AuthPage mode="login" />} /><Route path="/register" element={<AuthPage mode="register" />} /><Route path="/diagnosis" element={<DiagnosisFlow />} /><Route path="/technicians" element={<TechnicianListPage />} /><Route path="/technicians/:id" element={<TechnicianProfilePage />} /><Route element={<ProtectedRoute role="CUSTOMER" />}><Route path="/booking/:technicianId" element={<BookingPage />} /><Route path="/customer/repairs" element={<BookingListPage />} /><Route path="/customer/repairs/:id" element={<BookingDetailPage />} /><Route path="/customer/dashboard" element={<CustomerDashboard />} /><Route path="/customer/repairs/new" element={<DiagnosisFlow />} /></Route><Route element={<ProtectedRoute role="TECHNICIAN" />}><Route path="/technician/dashboard" element={<TechnicianDashboard />} /><Route path="/technician/jobs" element={<TechnicianDashboard />} /></Route><Route element={<ProtectedRoute />}><Route path="/profile" element={<ProfilePage />} /></Route><Route path="*" element={<Navigate to="/" replace />} /></Route></Routes> }
