const ROLES = ['CUSTOMER', 'TECHNICIAN', 'ADMIN'];

const REPAIR_STATUSES = [
  'SEARCHING',
  'ACCEPTED',
  'TECHNICIAN_ON_WAY',
  'ARRIVED',
  'DIAGNOSING',
  'ESTIMATE_SENT',
  'CUSTOMER_APPROVED',
  'IN_PROGRESS',
  'COMPLETED',
  'CANCELLED',
];

const VERIFICATION_STATUSES = ['PENDING', 'VERIFIED', 'REJECTED'];
const ESTIMATE_STATUSES = ['SENT', 'APPROVED', 'REJECTED', 'EXPIRED'];

module.exports = {
  ROLES,
  REPAIR_STATUSES,
  VERIFICATION_STATUSES,
  ESTIMATE_STATUSES,
};
